# 배열의 생성 및 조작

In [7]:
import numpy as np

# 1. np.array([값들])

In [ ]:
list1 = [1,2,3]
arr1 = np.array(list1)

# 초기화할 값을 지정하여 배열 생성
arr2 = np.array([1,2,3])

# 2. np.arange() -수의 순차적인 증감을 이용하여 배열 생성

In [ ]:
# np.arange([start, ]stop [, step])
# start: 시작 값 (생략가능, 기본값 0)
# stop: 끝 값(필수)
# step: 증감 값(생략 가능, 기본값 1)

# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr3 = np.arange(0,10)
# arr3 = np.arange(0, 10, 1)
# [0,1, 2, 3, 4, 5, 6, 7, 8, 9]
arr4 = np.arange(1, 10)
# [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr5 = np.arange(1, 10, 2)
# [1, 3, 5, 7, 9]
arr6 = np.arange(10, 1, -1)
# [10, 9, 8, 7, 6, 5, 4, 3, 2]
arr7 = np.arange(10, 1, -2)
# [10, 8, 6, 4, 2]

print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)


[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2]
[10  8  6  4  2]


# 3. np.zeros() - 0으로 초기화된 배열 생성

In [ ]:
# 1차원 배열
np.zeros(5)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 2차원 배열
# np.zeros((행, 열))
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# 3차원 배열
# np.zeros((층, 행, 열))
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# 4. np.ones() - 1로 초기화된 배열 생성

In [13]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

# 5. np.random.random() - 랜던값 배열 생성
- 0이상~1미만 사이의 무작위 수로 배열 생성

In [15]:
np.random.rand(2,3)

array([[0.31478674, 0.4734287 , 0.91585658],
       [0.79624447, 0.28553438, 0.85495872]])

# 6. np.empty() - 초기화 되지 않는 배열(빠름)

In [ ]:
np.empty(5)

[0. 0. 0. 0. 0.]
