# 배열의 생성 및 조작

In [50]:
import numpy as np

# 배열생성

# 1. np.array([값들])

In [51]:
list1 = [1,2,3]
arr1 = np.array(list1)

# 초기화할 값을 지정하여 배열 생성
arr2 = np.array([1,2,3])

# 2. np.arange() -수의 순차적인 증감을 이용하여 배열 생성

In [52]:
# np.arange([start, ]stop [, step])
# start: 시작 값 (생략가능, 기본값 0)
# stop: 끝 값(필수)
# step: 증감 값(생략 가능, 기본값 1)

# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr3 = np.arange(0,10)
# arr3 = np.arange(0, 10, 1)
# [0,1, 2, 3, 4, 5, 6, 7, 8, 9]
arr4 = np.arange(1, 10)
# [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr5 = np.arange(1, 10, 2)
# [1, 3, 5, 7, 9]
arr6 = np.arange(10, 1, -1)
# [10, 9, 8, 7, 6, 5, 4, 3, 2]
arr7 = np.arange(10, 1, -2)
# [10, 8, 6, 4, 2]

print(arr3)
print(arr4)
print(arr5)
print(arr6)
print(arr7)


[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2]
[10  8  6  4  2]


# 3. np.zeros() - 0으로 초기화된 배열 생성

In [53]:
# 1차원 배열
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
# 2차원 배열
# np.zeros((행, 열))
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
# 3차원 배열
# np.zeros((층, 행, 열))
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# 4. np.ones() - 1로 초기화된 배열 생성

In [56]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

# 5. np.random.random() - 랜던값 배열 생성
- 0이상~1미만 사이의 무작위 수로 배열 생성

In [57]:
np.random.rand(2,3)

array([[0.16093033, 0.91145402, 0.91160228],
       [0.45712764, 0.46879362, 0.7886919 ]])

# 6. np.empty() - 초기화 되지 않는 배열(빠름)

In [58]:
np.empty(5)

array([0., 0., 0., 0., 0.])

# 7. np.random.rand() - 랜덤값 배열

In [59]:
np.random.rand(2,3)

array([[0.34941629, 0.81372915, 0.42145795],
       [0.11388965, 0.22372486, 0.86642162]])

# 8. reshape() - 배열 차원 변형

In [60]:
arr2 = np.arange(16) # 1차원 배열
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [61]:
# 1차원을 2차원으로 변형
arr2.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
# 1차원을 3차원으로 변형
arr2.reshape(2,2,4)  #(2덩어리, 2행, 4열)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

## 배열 속성 확인 및 타입 변환
- shape: 각 차원의 크기
- dtype: 데이터 타입
- astype(): 데이터 타입 변환

In [63]:
arr2.shape

(16,)

In [64]:
arr2.dtype

dtype('int64')

In [65]:
arr2.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [66]:
## 배열의 저장과 불러오기

In [67]:
### 배열 저장하기 - np.save()
- np.save(저장할 파일명, 배열명): .npy 형식으로 저장

SyntaxError: invalid syntax. Perhaps you forgot a comma? (276614763.py, line 2)

In [ ]:
# 배열 생성 및 변환
# 메서드 체이닝: 메서드를 연속적으로 호출하는 방식
# - 모듈.함수().메서드()
arr = np.arange(10).reshape(2, 5) # 2행 5열로 바꿨다
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# 배열 저장하기: array.npy
np.save('array', arr)

### 배열 불러오기  - np.load()
- np.load('파일명'): 배열 불러오기

In [ ]:
load_arr = np.load('array.npy')
print(load_arr)
    

[[0 1 2 3 4]
 [5 6 7 8 9]]


# 배열의 압축된 형식 - npz 형식
- np.savez(저장할 파일명, 배열명1, 배열명2, ...): .npz 형식으로 저장
- np.savez_compressed(저장할 파일명, 배열명1, 배열명2, ...): .npz 형식으로 압축하여 저장

In [ ]:
### 1. np.savez() - 압축된 npy 파일 생성

In [ ]:
# 여러 배열 생성
arr1 = np.arange(10)
arr2 = np.arange(20).reshape(4, 5)
arr3 = np.random.rand(3,3)

In [ ]:
# 여러 배열을 하나의 파일로 저장
np.savez('multiple_arrays', first_array=arr1, second_array=arr2, third_array=arr3)

# 또는 이름 없이 저장
np.savez('arrays_no_names', arr1, arr2, arr3)

In [ ]:
### 2. npz 파일 불러오기 - np.load()

In [ ]:
# npz 파일 불러오기
loaded_date = np.load('multiple_arrays.npz')

# 저장된 배열 이름 확인
print(loaded_date.files)

['first_array', 'second_array', 'third_array']


In [68]:
#  개별 배열 접근
print(loaded_date['first_array'])
print(loaded_date['second_array'])
print(loaded_date['third_array'])

[1 2 3]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 또는 변수로 할당
arr1_loaded = loaded_data['first_array']
arr2_loaded = loaded_data['second_array']
arr3_loaded = loaded_data['third_array']

In [ ]:
# 사용 후 파일 닫기
loaded_data.close()

### 3. 압축 저장 - np.savez_compressed()

In [71]:
# 압축하여 저장(파일 크기 절약)
np.savez_compressed('compressed_arrays', data1=arr1, data2=arr2, data3=arr3)