#  최신 표준: Generator 객체 사용법 (추천)

In [3]:
import numpy as np

# 1. 최신 표준 Generator 생성
rng = np.random.default_rng()
print(rng)

Generator(PCG64)


## rng.integers(low, high, size): 정수 무작위 추출

In [11]:
# 1 이상 46 미만(1~45)의 숫자 중 6개를 1차원 배열로 추출
lotto = rng.integers(1, 46, size=6)
print(lotto)  # 예: [12 45  3 24 18  7]

# 0 이상 10 미만의 정수로 채워진 2행 3열짜리 배열 생성
matrix_int = rng.integers(0, 10, size=(2, 3))
print(matrix_int)

[24 43 42  7 36 39]
[[9 2 7]
 [9 2 8]]


## rng.random(size): 0.0 이상 1.0 미만의 실수 추출

In [5]:
# 0.0 ~ 1.0 사이의 실수로 채워진 3행 2열 배열 생성
matrix_float = rng.random((3, 2))
print(matrix_float)

[[0.74109051 0.43394025]
 [0.20742835 0.01994561]
 [0.10141733 0.85233719]]


## rng.choice(a, size, replace): 샘플 추출 (복원/비복원)

In [8]:
items = ['Apple', 'Banana', 'Orange', 'Grape']

# 중복을 허용하여 2개 선택 (기본값: replace=True)
print(rng.choice(items, size=2))

# 중복 없이 3개 선택 (비복원 추출)
print(rng.choice(items, size=3, replace=False))

['Banana' 'Banana']
['Apple' 'Grape' 'Orange']


## rng.shuffle(x)/rng.permutation(x): 무작위 무작위 셔플

In [9]:
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.permutation(arr)
print("원본:", arr)       # [1, 2, 3, 4, 5] 그대로 유지
print("셔플본:", shuffled) # 무작위 뒤섞인 배열

원본: [1 2 3 4 5]
셔플본: [4 1 5 2 3]


In [10]:
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.shuffle(arr)
print("원본:", arr)       # 원본이 변경
print("셔플본:", shuffled) # 반환값이 없음(None)

원본: [2 5 4 3 1]
셔플본: None


# 확률 분포 기반 난수 생성 (통계·머신러닝 필수)

## rng.normal(loc, scale, size): 정규 분포 (Gaussian)

In [13]:
# 평균 0, 표준편차 1인 표준정규분포를 따르는 데이터 10,000개 생성
normal_data = rng.normal(loc=0.0, scale=1.0, size=10000)
print(normal_data)

[ 1.20331967  0.41603688  0.18519511 ... -2.03105081  1.36354187
  0.29263234]


## rng.uniform(low, high, size): 균등 분포 (Uniform)

In [14]:
# 10.0부터 20.0 사이에서 균등한 확률로 5개 추출 (로또 나올때 1이 나올 확률, 2가 나올 확률 균등하게 1/6)
uniform_data = rng.uniform(10.0, 20.0, size=5)
print(uniform_data)

[18.32629184 19.45506599 12.10075497 18.75214196 12.06349141]
